---
title: "Big Data and Social Science"
subtitle: A Practical Guide to Methods and Tools
author:
- Ian Foster, Rayid Ghani, Ron S. Jarmin, Frauke Kreuter and Julia Lane
bibliography:
- book.bib
- parallel.bib
- reclink.bib
lot: yes
lof: yes
documentclass: krantz
github-repo: Coleridge-Initiative/big-data-and-social-science
site: bookdown::bookdown_site
link-citations: yes
biblio-style: apalike
---

# Preface {-}

The class on which this book is based was created in response to a very real challenge: how to introduce new ideas and methodologies about economic and social measurement into a workplace focused on producing high-quality statistics.  We are deeply grateful for the inspiration and support of Census Bureau Director John Thompson and Deputy Director Nancy Potok in designing and implementing the initial class content and structure.

As with any book, there are many people to be thanked. We are grateful to the over 450 participants in the Applied Data Analytics classes that have been delivered over the past three years. The Coleridge Initiative team at New York University, the University of Maryland and the University of Chicago were critical in shaping the format and structure - we are particularly grateful to Clayton Hunter, Jody Derezinski Williams, Graham Henke, Jonathan Morgan, Drew Gordon, Avishek Kumar, and Brian Kim.

We are also grateful to the students of three "Big Data for Federal Statistics" classes in which we piloted the first edition of this book, and to the instructors and speakers beyond those who  contributed as authors to this edited volume---Dan Black, Nick Collier, Ophir Frieder, Lee Giles, Bob Goerge, Laure Haak, Madian Khabsa, Jonathan Ozik, Ben Shneiderman, and Abe Usher. The book would not exist without them.

We thank Trent Buskirk, Davon Clarke, Chase Coleman, Stephanie Eckman, Matt Gee, Laurel Haak, Jen Helsby, Madian Khabsa, Ulrich Kohler, Charlotte Oslund, Rod Little, Arnaud Sahuguet, Tim Savage, Severin Thaler, and Joe Walsh for their helpful comments on drafts of this material. In particular we thank Stas Kolenikov for a very detailed review of the first edition.

We also owe a great debt to the copyeditor, Richard Leigh; the project editor, Charlotte Byrnes; and the publisher, Rob Calver, for their hard work and dedication.
